### ISSUE TITLE
Not found: /faucet/faucet.html

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/xkr-website#30]
When pressing the "tap" button to get XKR in Hugin Messenger it redirects to https://kryptokrona.org/faucet/faucet.html?address=<address>

But I get the error:

Not found: /faucet/faucet.html
Error: Not found: /faucet/faucet.html

**Comment by DanielBoye** [comment]
@mjovanc This is because the faucet is not an HTML file. Idk if this has changed but the faucet is under https://kryptokrona.org/faucet. Inside the /faucet there is a index.svelte, but it loads it in anyway, as for any website.

So to fix your problem, just change the link to https://kryptokrona.org/faucet and it should work.
